s-db:
  autodiscovery: "17540617"
  client_id: "43566c4218f64415b6a81e799c739331"
  client_secret: ""
http:
  port: "8082"
  path: "dbUsers"
  host: "localhost"
sql:
  port: "3306"
  host: "sql5.freemysqlhosting.net"
  database: "sql5463008"
  password: "5g61yHQkun" # TO CONFIGURE
  username: "sql5463008"