# Builds the project on every pull request
name: Build
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-mvn-     
      - name: Maven Settings
        env:
          MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_MULESOFT_SETTINGS_XML }}
        run:
          echo $MAVEN_SETTINGS_XML | base64 -d > ${{ github.workspace }}/settings.xml
      - name: Build with Maven
        run: 
          mvn -B package -s ${{ github.workspace }}/settings.xml
